### ISSUE TITLE
URL Failures

### ISSUE THREAD

**Issue by rcstone** [ransomvik/optiv_TA_threat#1]
when executing optiv_threat_lists.py the following urls failed to load for me:
1)'http://www.binarydefense.com/banlist.txt'
          Reason: Remote server rejected post method
          Fix:  change line 878
                  from:    raw_threatlist = getUrl(urlList[2].strip('\n'),'true')
                  to:        raw_threatlist = getUrl(urlList[2].strip('\n'),'false')

2)'https://reputation.alienvault.com/reputation.generic'
          Reason: SSLv3 handshake failure (server does not accept SSLv3)
          Fix: change URL to use HTTP but user updating SSL libs may also help

3)https://zeustracker.abuse.ch/blocklist.php?download=ipblocklist
   https://palevotracker.abuse.ch/blocklists.php?download=ipblocklist
   https://ransomwaretracker.abuse.ch/downloads/RW_IPBL.txt
   https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
   https://ransomwaretracker.abuse.ch/downloads/RW_URLBL.txt
         Reason: Page not found
         Fix: Change link to HTTP
                I have no idea why this fix works as the http links are redirected to https in my browser and I assume the same thing happens with urllib2.

Thanks for putting this out for everyone.

**Comment by ransomvik** [comment]
YW.
This should be fixed in 3.32.
