### ISSUE TITLE
Parsing Error for ransomware_Abuse_CH_URLs

### ISSUE THREAD

**Issue by rcstone** [ransomvik/optiv_TA_threat#4]
results such as the following were in  the ransomware_Abuse_CH_URLs threat list
url=################
url=#

Fixed (I think) by adding an additional conditional statement to line 220 in bin/optiv_threat_lists.py
```python
 if (len(line) > 2 and not line.lstrip().startswith('#')):
```

**Comment by ransomvik** [comment]
Incorporated change into 3.32. Thanks for the reports.
